platform :ios, '16.0'
use_frameworks! :linkage => :static
install! 'cocoapods', :disable_input_output_paths => true

target 'App' do
  use_frameworks! :linkage => :static
  pod 'RevenueCat', '~> 5.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.8'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
